version: '3'

services:

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-root}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "${WORDPRESS_DB_PASSWORD:-password}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "${PORT:-1234}:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-root}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-password}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
    volumes:
      - ./src:/var/www/html
    networks:
      - wordpress

networks:
  wordpress: